# Generated by Django 3.2.7 on 2021-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaltingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.CharField(max_length=25)),
                ('player0', models.BooleanField(default=False)),
                ('player1', models.BooleanField(default=False)),
                ('time_created', models.TimeField(auto_now=True)),
            ],
        ),
    ]
